// Gate 7 Batch 3E-B1B: executable N1 canonicalization through the one production adapter, scripts/media-ingest-local.ts, on generated
// synthetic media only (tests/support/canonical-media-fixtures.ts): no owner footage, no model, no network. Fixture authorizations declare
// generated bytes as owner_supplied 1.1.0 roots ONLY to exercise the adapter's own checks; they are not owner media and prove nothing about
// real footage. Every claim about published bytes is re-checked here by an independent probe and independent frame listings, never only by
// the adapter's own report. The adapter's exports are read through its module namespace, so each test fails on its own before B1B.
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { after, before, test, type TestContext } from "node:test";
import { chmod, copyFile, mkdir, mkdtemp, readFile, readdir, realpath, rm, stat, symlink, unlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { canonicalSerialize } from "../packages/domain/serialization.js";
import { evaluateInputConformance, parseProbeJson, type ConformanceInput } from "../packages/edit-render/index.js";
import { identify } from "../packages/editorial/common.js";
import * as ownerMedia from "../packages/edit-render/owner-media.js";
import * as ingest from "../packages/media-ingest/index.js";
import * as local from "../scripts/media-ingest-local.js";
import * as authority from "../scripts/edit-render-owner-media-authority-local.js";
import { observeMediaSpawns, PINNED_TOOL_ROOT } from "./support/edit-render-media.js";
import { generateFixture, independentListing, independentProbe, sha256File, withoutSar, type FixtureSpec } from "./support/canonical-media-fixtures.js";

// ---------------------------------------------------------------- the adapter's surface, read through its namespace
type Json = Record<string, unknown>;
interface Request { sourcePath: string; rootAuthorization: unknown; toolRoot: string; workspaceRoot: string; clock: { now(): string };
  allowedPurposes?: string[]; limits?: { maxOutputBytes?: number; canonicalizationTimeoutMilliseconds?: number };
  instrumentation?: { beforeProcess?: (context: { role: string }) => Promise<void>; beforePublication?: () => Promise<void> } }
interface Result { outcome: string; classification: Json; source: Json; computationId?: string; derivation?: Json; authorization?: Json; output?: Json;
  publication?: string; cache?: string; evidence?: Json }
const A = local as unknown as Record<string, unknown>;
const canonicalize = (request: Request): Promise<Result> => (A["canonicalizeLocalMedia"] as (r: Request) => Promise<Result>)(request);
async function refusal(run: () => Promise<unknown>, message?: RegExp): Promise<string> {
  try { await run(); } catch (error) {
    const ErrorClass = A["CanonicalIngestError"] as (new (...args: never[]) => Error) | undefined;
    if (ErrorClass !== undefined && error instanceof ErrorClass) {
      const code = (error as { code?: unknown }).code;
      assert.ok((A["CANONICAL_INGEST_ERROR_CODES"] as readonly string[]).includes(String(code)), String(code));
      assert.doesNotMatch(error.message, /[A-Za-z]:\\|\/Users\/|\.local-media/, "a refusal never carries a location");
      if (message !== undefined) assert.match(error.message, message);
      return String(code);
    }
    assert.fail(`expected an owned canonical-ingest refusal, received ${String(error)}`);
  }
  assert.fail("expected an owned canonical-ingest refusal");
}
const sha256 = (value: string | Uint8Array) => createHash("sha256").update(value).digest("hex");

// ---------------------------------------------------------------- generated fixtures (shared, never mutated) and per-test workspaces
const CLOCK = Object.freeze({ now: () => "2026-10-05T08:00:00.000Z" });
const SCOPE = { creatorId: "creator_b1b_media", projectId: "project_b1b_media" }, OTHER = { creatorId: "creator_b1b_other", projectId: "project_b1b_other" };
interface Fixture { path: string; contentHash: string; sizeBytes: number }
const root = (f: Fixture, patch: Json = {}): Json => ({ manifestType: "AuthorizedFootage", schemaVersion: "1.1.0", contentHash: f.contentHash, sizeBytes: f.sizeBytes,
  sourceType: "owner_supplied", authorizationBasis: "owner_created", allowedPurposes: ["local_footage_analysis", "local_evaluation"], dateAdded: "2026-10-01T00:00:00.000Z",
  ...SCOPE, canonicalizationConsent: "local_media_canonicalization", ...patch });
const v1 = (f: Fixture, patch: Json = {}): Json => { const value = root(f, { schemaVersion: "1.0.0", ...patch }); delete value.canonicalizationConsent; return value; };
let base = "", fixtures = "";
const SPECS: Record<string, FixtureSpec & { name: string }> = {
  video: { name: "n1-video.mp4", audio: "none" }, pcm: { name: "n1-pcm.mov", audio: "pcm" }, aac: { name: "n1-aac.mp4", audio: "aac" },
  other: { name: "n1-other-pixels.mp4", audio: "none", pattern: "smptebars" }, otherTone: { name: "n1-pcm-other-tone.mov", audio: "pcm", tone: 330 },
  direct: { name: "direct-square.mp4", audio: "none", sar: "square" }, sei: { name: "sei-kept.mp4", audio: "none", sei: true },
  nonSquare: { name: "non-square.mp4", audio: "none", sar: "4:3" }, yuv444: { name: "yuv444.mp4", audio: "none", pixelFormat: "yuv444p" },
  vfr: { name: "vfr.mp4", audio: "none", timing: "vfr" },
};
const F: Record<string, Fixture> = {};
before(async () => {
  base = await realpath(await mkdtemp(join(tmpdir(), "gate7-b1b-media-")));
  fixtures = join(base, "fixtures"); await mkdir(fixtures);
  for (const [key, spec] of Object.entries(SPECS)) {
    const path = await generateFixture(fixtures, spec.name, spec);
    F[key] = { path, ...(await sha256File(path)) };
  }
  const video = await readFile(F.video!.path);
  await writeFile(join(fixtures, "truncated.mp4"), video.subarray(0, Math.floor(video.length / 2)));
  await writeFile(join(fixtures, "random.mp4"), Uint8Array.from({ length: 4096 }, (_, i) => (i * 131 + 7) % 251));
  for (const key of ["truncated", "random"]) { const path = join(fixtures, `${key}.mp4`); F[key] = { path, ...(await sha256File(path)) }; }
});
after(() => rm(base, { recursive: true, force: true }));

async function scratch(t: TestContext, label: string): Promise<string> {
  const directory = await realpath(await mkdtemp(join(base, `${label}-`)));
  t.after(() => rm(directory, { recursive: true, force: true }));
  return directory;
}
/** A private copy of a fixture in its own directory, for tests that change or remove a source. */
async function copyOf(t: TestContext, f: Fixture, label: string): Promise<Fixture> {
  const directory = await scratch(t, `src-${label}`), path = join(directory, "source.mp4");
  await copyFile(f.path, path);
  return { ...f, path };
}
function request(f: Fixture, workspaceRoot: string, patch: Partial<Request> = {}): Request {
  return { sourcePath: f.path, rootAuthorization: root(f), toolRoot: PINNED_TOOL_ROOT, workspaceRoot, clock: CLOCK, ...patch };
}
const store = (workspace: string, ...parts: string[]) => join(workspace, ...ownerMedia.CANONICAL_STORE.directory, ...parts);
const objectPath = (workspace: string, hash: string) => store(workspace, ownerMedia.CANONICAL_STORE.objects, ownerMedia.canonicalObjectName(hash));
const recordPath = (workspace: string, computationId: string) => store(workspace, ownerMedia.CANONICAL_STORE.computations, ownerMedia.canonicalComputationRecordName(computationId));
async function entries(path: string): Promise<string[] | null> { try { return (await readdir(path)).sort(); } catch { return null; } }
/** Nothing trusted or pending is left in a store: the state every refused operation must leave. */
async function assertNothingPublished(workspace: string, label: string): Promise<void> {
  for (const name of ["objects", "computations", "pending"] as const) {
    const listed = await entries(store(workspace, ownerMedia.CANONICAL_STORE[name]));
    assert.ok(listed === null || listed.length === 0, `${label}: ${name} holds ${JSON.stringify(listed)}`);
  }
}
const onceBy = new Map<string, Promise<{ workspace: string; result: Result }>>();
/** One shared, successful canonicalization per fixture (its workspace is never mutated). */
function canonicalOnce(key: string): Promise<{ workspace: string; result: Result }> {
  let value = onceBy.get(key);
  if (value === undefined) {
    value = (async () => { const workspace = await realpath(await mkdtemp(join(base, `shared-${key}-`))); return { workspace, result: await canonicalize(request(F[key]!, workspace)) }; })();
    onceBy.set(key, value);
  }
  return value;
}
const RECIPE_MARK = "h264_metadata=sample_aspect_ratio=1/1";

// ================================================================ the recipe, exactly
test("B1B-M01 the adapter executes exactly the accepted N1 template under the verified pinned runtime, fd-only, once", async t => {
  const workspace = await scratch(t, "m01"), observer = observeMediaSpawns(); t.after(observer.restore);
  const result = await canonicalize(request(F.video!, workspace));
  observer.restore();
  assert.equal(result.outcome, "NORMALIZE_N1");
  const recipe = observer.calls.filter(c => c.arguments.includes(RECIPE_MARK));
  assert.equal(recipe.length, 1, "exactly one recipe execution");
  assert.equal(recipe[0]!.tool, "ffmpeg");
  const argv = recipe[0]!.arguments, bound = argv[argv.indexOf("-fs") + 1]!;
  assert.match(bound, /^[1-9][0-9]*$/);
  assert.deepEqual(argv, ingest.N1_ARGV_TEMPLATE.map(token => token === "{input_fd}" ? "3" : token === "{output_fd}" ? "4" : token === "{max_output_bytes}" ? bound : token),
    "the declared template with only its three placeholders filled");
  assert.equal(ingest.N1_RECIPE.argvTemplateDigest, sha256(JSON.stringify(ingest.N1_ARGV_TEMPLATE)), "the accepted template digest is unchanged");
  assert.ok(observer.calls.every(c => (c.tool === "ffmpeg" || c.tool === "ffprobe") && c.arguments.includes("fd:")), "only the pinned tools, reading inherited descriptors");
  assert.ok(observer.calls.every(c => c.arguments.every(a => !a.includes(base))), "no location ever reaches a pinned process");
  assert.ok(observer.calls.every(c => c.arguments.filter(a => a === "-protocol_whitelist").length >= 1));
});

// ================================================================ B1-07 / B1-08 / B1-12 / B1-13 / B1-14 / B1-15 on every N1 fixture
test("B1-07 the canonical output's bytes differ from the source's", async () => {
  for (const key of ["video", "pcm", "aac"]) {
    const { workspace, result } = await canonicalOnce(key);
    assert.equal(result.outcome, "NORMALIZE_N1", key);
    const output = result.output as { contentHash: string; sizeBytes: number };
    assert.notEqual(output.contentHash, F[key]!.contentHash, key);
    assert.deepEqual(await sha256File(objectPath(workspace, output.contentHash)), { contentHash: output.contentHash, sizeBytes: output.sizeBytes }, `${key}: the published object is its name`);
  }
});

test("B1-08 the original bytes, size and hash are unchanged, and the source is never written", async t => {
  for (const key of ["video", "pcm", "aac"]) {
    const copy = await copyOf(t, F[key]!, `b108-${key}`), before = await stat(copy.path);
    const workspace = await scratch(t, `b108-${key}`), result = await canonicalize(request(copy, workspace));
    assert.equal(result.outcome, "NORMALIZE_N1");
    const after = await stat(copy.path);
    assert.deepEqual(await sha256File(copy.path), { contentHash: F[key]!.contentHash, sizeBytes: F[key]!.sizeBytes }, key);
    assert.equal(after.mtimeMs, before.mtimeMs, `${key}: never written`);
    assert.deepEqual((result.source as Json), { assetId: `asset_${F[key]!.contentHash}`, contentHash: F[key]!.contentHash, sizeBytes: F[key]!.sizeBytes });
  }
});

test("B1-12 the published output explicitly reports SAR 1:1 (independent probe); the source declared none", async () => {
  for (const key of ["video", "pcm", "aac"]) {
    const { workspace, result } = await canonicalOnce(key), hash = (result.output as { contentHash: string }).contentHash;
    const out = JSON.parse(await independentProbe(objectPath(workspace, hash))) as { streams: Json[] }, src = JSON.parse(await independentProbe(F[key]!.path)) as { streams: Json[] };
    assert.equal(out.streams.find(s => s.codec_type === "video")!.sample_aspect_ratio, "1:1", key);
    assert.equal(src.streams.find(s => s.codec_type === "video")!.sample_aspect_ratio, undefined, key);
    assert.equal(((result.derivation as Json).output as { verification: Json }).verification.outputSampleAspectRatio, "1:1");
  }
});

test("B1-13 decoded video, exact frame instants, frame count and frame table are unchanged (independent listings and probe)", async () => {
  for (const key of ["video", "pcm", "aac"]) {
    const { workspace, result } = await canonicalOnce(key), hash = (result.output as { contentHash: string }).contentHash, out = objectPath(workspace, hash);
    const [sourceListing, outputListing] = [await independentListing(F[key]!.path, "video"), await independentListing(out, "video")];
    assert.equal(withoutSar(outputListing), withoutSar(sourceListing), `${key}: every decoded frame (pts, dts, duration, size, MD5) is identical`);
    assert.ok(sourceListing.includes("#sar 0: 0/1") && outputListing.includes("#sar 0: 1/1"), `${key}: the SAR line is the only difference`);
    const frames = (text: string) => (JSON.parse(text) as { frames: { stream_index: number; pts: number }[]; streams: Json[] });
    const [s, o] = [frames(await independentProbe(F[key]!.path)), frames(await independentProbe(out))];
    const video = (p: ReturnType<typeof frames>) => ({ timeBase: p.streams.find(x => x.codec_type === "video")!.time_base, startPts: p.streams.find(x => x.codec_type === "video")!.start_pts,
      pts: p.frames.filter(f => f.stream_index === p.streams.find(x => x.codec_type === "video")!.index).map(f => f.pts) });
    assert.deepEqual(video(o), video(s), `${key}: exact instants`);
    assert.equal(video(s).pts.length, 60);
    const derivation = result.derivation as { classification: { video: { frameTableId: string; frameCount: number } }; output: { verification: Json } };
    assert.equal(derivation.output.verification.frameTableId, derivation.classification.video.frameTableId);
    assert.equal(derivation.output.verification.frameCount, 60);
    const decoded = derivation.output.verification.decodedVideo as Json;
    assert.equal(decoded.method, "pinned_runtime_decoded_frame_md5_v0");
    assert.equal(decoded.sourceDigest, decoded.outputDigest);
  }
});

test("B1-14 stream-copied audio keeps its payload, exact packet timing and sample structure (independent listings and probe)", async () => {
  for (const key of ["pcm", "aac"]) {
    const { workspace, result } = await canonicalOnce(key), hash = (result.output as { contentHash: string }).contentHash, out = objectPath(workspace, hash);
    const [s, o] = [await independentListing(F[key]!.path, "audio"), await independentListing(out, "audio")];
    assert.equal(o, s, `${key}: every packet's dts, pts, duration, size, payload MD5 and side data, with codec, rate, layout and extradata`);
    assert.match(s, /#tb 0: 1\/48000/);
    const audio = (text: string) => { const p = JSON.parse(text) as { frames: { stream_index: number; pts: number; nb_samples?: number }[]; streams: Json[] };
      const a = p.streams.find(x => x.codec_type === "audio")!;
      return { a, frames: p.frames.filter(f => f.stream_index === a.index).map(f => [f.pts, f.nb_samples]) }; };
    const [sa, oa] = [audio(await independentProbe(F[key]!.path)), audio(await independentProbe(out))];
    assert.deepEqual(oa, sa, `${key}: exact instants, sample counts, codec, rate, layout, time base and start`);
    assert.equal(sa.frames.reduce((n, f) => n + Number(f[1]), 0), 96_000);
    const verified = ((result.derivation as Json).output as { verification: { audio: Json } }).verification.audio;
    assert.deepEqual([verified.state, verified.method, verified.samples], ["stream_copied", "pinned_runtime_audio_packet_md5_v0", 96_000]);
    assert.equal(verified.sourceDigest, verified.outputDigest);
  }
  const { result } = await canonicalOnce("video");
  assert.deepEqual(((result.derivation as Json).output as { verification: { audio: Json } }).verification.audio, { state: "absent" });
});

test("B1-15 the output passes the unchanged strict renderer admission; the source does not", async () => {
  for (const key of ["video", "pcm", "aac"]) {
    const { workspace, result } = await canonicalOnce(key), hash = (result.output as { contentHash: string }).contentHash;
    const c = result.classification as { video: { frameCount: number; frameTableId: string; width: number; height: number; frameRate: { numerator: number; denominator: number } };
      audio: { state: string; sampleRateHz?: number; channelLayout?: "mono" | "stereo"; samples?: number } };
    const input: ConformanceInput = { video: { frameCount: c.video.frameCount, tableId: c.video.frameTableId, width: c.video.width, height: c.video.height, grid: c.video.frameRate },
      audio: c.audio.state === "present" ? { required: true, sampleRateHz: c.audio.sampleRateHz!, channelLayout: c.audio.channelLayout!, requiredSamples: c.audio.samples! } : { required: false } };
    assert.deepEqual(evaluateInputConformance(input, parseProbeJson(await independentProbe(objectPath(workspace, hash)))).outcome, { state: "conforms" }, key);
    assert.deepEqual(evaluateInputConformance(input, parseProbeJson(await independentProbe(F[key]!.path))).outcome,
      { state: "nonconforming", reasonCode: "source_video_nonconforming" }, key);
  }
});

// ================================================================ B1-11 determinism
test("B1-11 two independent canonicalizations in two fresh stores are byte-identical, with identical identities", async t => {
  for (const key of ["video", "aac"]) {
    const [w1, w2] = [await scratch(t, `b111a-${key}`), await scratch(t, `b111b-${key}`)];
    const [r1, r2] = [await canonicalize(request(F[key]!, w1)), await canonicalize(request(F[key]!, w2))];
    assert.equal(r1.publication, "published_by_this_operation"); assert.equal(r2.publication, "published_by_this_operation");
    const [o1, o2] = [r1.output as { contentHash: string }, r2.output as { contentHash: string }];
    assert.equal(o1.contentHash, o2.contentHash, key);
    assert.deepEqual(await readFile(objectPath(w1, o1.contentHash)), await readFile(objectPath(w2, o2.contentHash)));
    assert.equal(r1.computationId, r2.computationId);
    assert.deepEqual(r1.derivation, r2.derivation);
    assert.deepEqual(await readFile(recordPath(w1, r1.computationId!), "utf8"), await readFile(recordPath(w2, r2.computationId!), "utf8"));
  }
});

// ================================================================ DIRECT and REFUSE create nothing
test("B1B-D01 a strict-conforming source is DIRECT: nothing is copied, transcoded or remuxed and no store is touched", async t => {
  const workspace = await scratch(t, "d01"), observer = observeMediaSpawns(); t.after(observer.restore);
  for (const authorization of [root(F.direct!), v1(F.direct!)]) {
    const result = await canonicalize(request(F.direct!, workspace, { rootAuthorization: authorization }));
    assert.equal(result.outcome, "DIRECT");
    assert.equal((result.classification as Json).reasonCode, "renderer_conforms_unchanged");
    assert.deepEqual([result.derivation, result.authorization, result.output], [undefined, undefined, undefined]);
  }
  observer.restore();
  assert.equal(observer.calls.filter(c => c.arguments.includes(RECIPE_MARK)).length, 0, "the recipe never runs for DIRECT");
  assert.equal(await entries(join(workspace, ".local-media")), null, "no store is created");
});

test("B1B-R01 a refused source creates nothing: side data, non-square SAR, 4:4:4 and variable timing", async t => {
  const workspace = await scratch(t, "r01"), observer = observeMediaSpawns(); t.after(observer.restore);
  for (const [key, reason] of [["sei", "frame_side_data_present"], ["nonSquare", "sample_aspect_ratio_explicit_non_square"], ["yuv444", "renderer_nonconforming"],
    ["vfr", "renderer_nonconforming"]] as const) {
    const result = await canonicalize(request(F[key]!, workspace));
    assert.equal(result.outcome, "REFUSE", key);
    assert.equal((result.classification as Json).reasonCode, reason, key);
    assert.deepEqual([result.derivation, result.authorization, result.output], [undefined, undefined, undefined], key);
  }
  observer.restore();
  assert.equal(observer.calls.filter(c => c.arguments.includes(RECIPE_MARK)).length, 0);
  assert.equal(await entries(join(workspace, ".local-media")), null);
});

test("B1-24 corrupt and unsupported input fails closed and creates nothing", async t => {
  const workspace = await scratch(t, "b124");
  for (const key of ["truncated", "random"]) {
    const result = await canonicalize(request(F[key]!, workspace));
    assert.equal(result.outcome, "REFUSE", key);
    assert.deepEqual([(result.classification as Json).reasonCode, (result.classification as Json).basis], ["probe_invalid", "invalid_input"], key);
  }
  assert.equal(await entries(join(workspace, ".local-media")), null);
});

// ================================================================ B1-20 failed or partial output never becomes trusted
test("B1-20 a failed or partial output never becomes trusted: write bound, timeout, non-zero exit", async t => {
  const workspace = await scratch(t, "b120");
  // FFmpeg's -fs is a soft limit: it exits 0 with a truncated file larger than the bound. The adapter's own post-run bound refuses it.
  assert.equal(await refusal(() => canonicalize(request(F.pcm!, workspace, { limits: { maxOutputBytes: 4096 } }))), "output_invalid", "a write cut short by the byte bound");
  await assertNothingPublished(workspace, "byte bound");
  assert.equal(await refusal(() => canonicalize(request(F.pcm!, workspace, { limits: { canonicalizationTimeoutMilliseconds: 1 } }))), "process_timeout");
  await assertNothingPublished(workspace, "timeout");
  // The source is truncated in place after its verification and immediately before the recipe starts: FFmpeg exits non-zero.
  const copy = await copyOf(t, F.video!, "b120");
  const code = await refusal(() => canonicalize(request(copy, workspace, { instrumentation: { async beforeProcess({ role }) {
    if (role === "canonicalize") await writeFile(copy.path, (await readFile(copy.path)).subarray(0, 600)); } } })));
  assert.equal(code, "process_failed");
  await assertNothingPublished(workspace, "non-zero exit");
  for (const limits of [{ maxOutputBytes: 0 }, { maxOutputBytes: 1.5 }, { canonicalizationTimeoutMilliseconds: -1 }, { maxOutputBytes: 2 ** 60 },
    { canonicalizationTimeoutMilliseconds: 10 * 3_600_000 }, { other: 1 }]) {
    assert.equal(await refusal(() => canonicalize(request(F.video!, workspace, { limits: limits as never }))), "request_invalid", JSON.stringify(limits));
  }
});

// ================================================================ B1-21 concurrency / B1-22 cache hit / B1-23 tampered cache
test("B1-21 two concurrent operations of one computation publish once; the other re-verifies the winner", async t => {
  const workspace = await scratch(t, "b121");
  let arrived = 0, release: () => void = () => undefined;
  const barrier = new Promise<void>(resolve => { release = resolve; });
  const instrumentation = { async beforePublication() { arrived += 1; if (arrived === 2) release(); await barrier; } };
  const results = await Promise.all([canonicalize(request(F.aac!, workspace, { instrumentation })), canonicalize(request(F.aac!, workspace, { instrumentation }))]);
  assert.deepEqual(results.map(r => r.publication).sort(), ["existing_object_reverified", "published_by_this_operation"]);
  assert.deepEqual(results.map(r => r.cache), ["miss", "miss"], "both executed: neither could find the other's result yet");
  assert.deepEqual(results[0]!.derivation, results[1]!.derivation);
  assert.equal((await entries(store(workspace, "objects")))!.length, 1);
  assert.equal((await entries(store(workspace, "computations")))!.length, 1);
  assert.deepEqual(await entries(store(workspace, "pending")), []);
});

test("B1-22 a cache hit never re-executes the recipe and runs the full verification before any trust", async t => {
  const workspace = await scratch(t, "b122"), first = await canonicalize(request(F.pcm!, workspace));
  assert.deepEqual([first.cache, first.publication], ["miss", "published_by_this_operation"]);
  const observer = observeMediaSpawns(); t.after(observer.restore);
  const second = await canonicalize(request(F.pcm!, workspace));
  observer.restore();
  assert.deepEqual([second.cache, second.publication], ["hit", "existing_object_reverified"]);
  assert.equal(observer.calls.filter(c => c.arguments.includes(RECIPE_MARK)).length, 0, "no recipe process on a hit");
  assert.equal(observer.calls.filter(c => c.tool === "ffprobe").length, 2, "the source and the cached object are both probed");
  assert.equal(observer.calls.filter(c => c.tool === "ffmpeg" && c.arguments.includes("framemd5")).length, 4, "decoded video and audio packets of both are re-measured");
  assert.deepEqual(second.derivation, first.derivation);
  assert.deepEqual(second.authorization, first.authorization);
});

test("B1-23 a tampered cache refuses and is never repaired", async t => {
  const workspace = await scratch(t, "b123"), first = await canonicalize(request(F.video!, workspace));
  const hash = (first.output as { contentHash: string }).contentHash, object = objectPath(workspace, hash), record = recordPath(workspace, first.computationId!);
  const original = await readFile(object), recordBytes = await readFile(record, "utf8");
  // (a) the cached object's bytes are changed in place
  const tampered = Uint8Array.from(original); tampered[tampered.length - 9] = (tampered[tampered.length - 9]! + 1) % 256;
  await chmod(object, 0o666); await writeFile(object, tampered);
  assert.equal(await refusal(() => canonicalize(request(F.video!, workspace))), "cache_corrupt");
  assert.deepEqual(await readFile(object), Buffer.from(tampered), "never repaired: the tampered object is left exactly as found");
  assert.deepEqual((await entries(store(workspace, "objects")))!, [ownerMedia.canonicalObjectName(hash)]);
  await writeFile(object, original);
  // (b) the record is not stored exactly as published
  await writeFile(record, recordBytes.replace("{", "{ "));
  assert.equal(await refusal(() => canonicalize(request(F.video!, workspace))), "cache_corrupt");
  // (c) the record's content is changed and its own identity recomputed
  const forged = JSON.parse(recordBytes) as Json; delete forged.recordId; (forged.output as Json).sizeBytes = (first.output as { sizeBytes: number }).sizeBytes + 1;
  await writeFile(record, `${canonicalSerialize(identify("canonical_computation_record_v0", "recordId", forged))}\n`);
  assert.equal(await refusal(() => canonicalize(request(F.video!, workspace))), "cache_corrupt");
  // (d) a malformed object under its own content name, with the record re-identified to name exactly it: the probe of it fails, so no trust
  const malformed = Uint8Array.from(original.subarray(0, 1000)), malformedHash = sha256(malformed);
  await writeFile(objectPath(workspace, malformedHash), malformed);
  const pointed = JSON.parse(recordBytes) as Json; delete pointed.recordId;
  Object.assign(pointed.output as Json, { assetId: `asset_${malformedHash}`, contentHash: malformedHash, sizeBytes: malformed.length });
  await writeFile(record, `${canonicalSerialize(identify("canonical_computation_record_v0", "recordId", pointed))}\n`);
  assert.equal(await refusal(() => canonicalize(request(F.video!, workspace)), /^The output is not a readable media file\.$/), "cache_corrupt",
    "an unreadable cached output is never trusted: refused by its failed probe, not by any earlier check");
  await writeFile(record, recordBytes);
  const again = await canonicalize(request(F.video!, workspace));
  assert.deepEqual([again.cache, again.derivation], ["hit", first.derivation], "the restored entry verifies again");
});

// ================================================================ B1B-01 .. B1B-04 probe-to-bytes binding and substitution
test("B1B-01 a source probe of any bytes other than the verified source refuses", async t => {
  const workspace = await scratch(t, "b1b01");
  const changed = await copyOf(t, F.video!, "b1b01a");
  assert.equal(await refusal(() => canonicalize(request(changed, workspace, { instrumentation: { async beforeProcess({ role }) {
    if (role !== "source_probe") return;
    const bytes = await readFile(changed.path); bytes[bytes.length - 40] = (bytes[bytes.length - 40]! + 1) % 256; await writeFile(changed.path, bytes); } } }))), "source_changed",
  "the probed bytes changed under the verified handle");
  const replaced = await copyOf(t, F.video!, "b1b01b");
  assert.equal(await refusal(() => canonicalize(request(replaced, workspace, { instrumentation: { async beforeProcess({ role }) {
    if (role === "source_probe") { await unlink(replaced.path); await copyFile(F.other!.path, replaced.path); } } } }))), "source_changed",
  "another source's bytes under the same name are another file");
  const afterProbe = await copyOf(t, F.video!, "b1b01c");
  assert.equal(await refusal(() => canonicalize(request(afterProbe, workspace, { instrumentation: { async beforeProcess({ role }) {
    if (role !== "source_video_digest") return;
    const bytes = await readFile(afterProbe.path); bytes[bytes.length - 40] = (bytes[bytes.length - 40]! + 1) % 256; await writeFile(afterProbe.path, bytes); } } }))), "source_changed",
  "bytes changed after the probe, while a later measurement read them");
  await assertNothingPublished(workspace, "B1B-01");
});

test("B1B-02 an output probe of any bytes other than the verified pending output refuses", async t => {
  const workspace = await scratch(t, "b1b02");
  assert.equal(await refusal(() => canonicalize(request(F.video!, workspace, { instrumentation: { async beforeProcess({ role }) {
    if (role !== "output_probe") return;
    const pending = (await entries(store(workspace, "pending")))!.filter(n => n.endsWith(".mp4"));
    assert.equal(pending.length, 1);
    const path = store(workspace, "pending", pending[0]!), bytes = await readFile(path); bytes[bytes.length - 40] = (bytes[bytes.length - 40]! + 1) % 256; await writeFile(path, bytes);
  } } }))), "output_invalid");
  await assertNothingPublished(workspace, "B1B-02");
  // The output bytes changed after its probe, while the decoded-frame measurement read them.
  const later = await scratch(t, "b1b02b");
  assert.equal(await refusal(() => canonicalize(request(F.video!, later, { instrumentation: { async beforeProcess({ role }) {
    if (role !== "output_video_digest") return;
    const pending = (await entries(store(later, "pending")))!.filter(n => n.endsWith(".mp4"));
    const path = store(later, "pending", pending[0]!), bytes = await readFile(path); bytes[bytes.length - 40] = (bytes[bytes.length - 40]! + 1) % 256; await writeFile(path, bytes);
  } } }))), "output_invalid");
  await assertNothingPublished(later, "B1B-02 after probe");
});

test("B1B-03 a source mutated while the recipe reads it refuses, and nothing is published", async t => {
  const workspace = await scratch(t, "b1b03"), copy = await copyOf(t, F.pcm!, "b1b03");
  assert.equal(await refusal(() => canonicalize(request(copy, workspace, { instrumentation: { async beforeProcess({ role }) {
    if (role !== "canonicalize") return;
    const bytes = await readFile(copy.path); bytes[4000] = (bytes[4000]! + 1) % 256; await writeFile(copy.path, bytes); } } }))), "source_changed");
  await assertNothingPublished(workspace, "B1B-03");
});

test("B1B-04 canonical bytes of another computation can never be substituted", async t => {
  // (a) a cached record of this computation repointed at another computation's verified object, its identity recomputed
  const workspace = await scratch(t, "b1b04a"), mine = await canonicalize(request(F.video!, workspace)), theirs = await canonicalize(request(F.other!, workspace));
  const record = JSON.parse(await readFile(recordPath(workspace, mine.computationId!), "utf8")) as Json, other = JSON.parse(await readFile(recordPath(workspace, theirs.computationId!), "utf8")) as Json;
  delete record.recordId; record.output = other.output;
  await writeFile(recordPath(workspace, mine.computationId!), `${canonicalSerialize(identify("canonical_computation_record_v0", "recordId", record))}\n`);
  assert.equal(await refusal(() => canonicalize(request(F.video!, workspace))), "cache_corrupt", "identical timing and frame table, other pixels");
  // (b) another computation's record copied over this computation's record
  await writeFile(recordPath(workspace, mine.computationId!), await readFile(recordPath(workspace, theirs.computationId!)));
  assert.equal(await refusal(() => canonicalize(request(F.video!, workspace))), "cache_corrupt");
  // (c) another computation's bytes pre-planted under this computation's content name are never overwritten or trusted
  const planted = await scratch(t, "b1b04c"), expected = (mine.output as { contentHash: string }).contentHash;
  await mkdir(store(planted, "objects"), { recursive: true });
  await copyFile(objectPath(workspace, (theirs.output as { contentHash: string }).contentHash), objectPath(planted, expected));
  const plantedBytes = await readFile(objectPath(planted, expected));
  assert.equal(await refusal(() => canonicalize(request(F.video!, planted))), "publication_conflict");
  assert.deepEqual(await readFile(objectPath(planted, expected)), plantedBytes, "the occupied name is left untouched");
  assert.deepEqual(await entries(store(planted, "computations")), [], "no record names unverified bytes");
  // (d) the verified, sealed pending object replaced by another computation's bytes immediately before publication
  const swapped = await scratch(t, "b1b04d"), otherBytes = await readFile(objectPath(workspace, (theirs.output as { contentHash: string }).contentHash));
  assert.equal(await refusal(() => canonicalize(request(F.video!, swapped, { instrumentation: { async beforePublication() {
    const pending = (await entries(store(swapped, "pending")))!.filter(n => n.endsWith(".mp4"));
    const path = store(swapped, "pending", pending[0]!); await unlink(path); await writeFile(path, otherBytes); } } }))), "output_invalid");
  assert.deepEqual(await entries(store(swapped, "objects")), []);
  assert.deepEqual(await entries(store(swapped, "computations")), []);
});

// ================================================================ the source's lifecycle during an operation
test("B1B-M02 a source that disappears during the operation refuses", async t => {
  const workspace = await scratch(t, "m02"), copy = await copyOf(t, F.aac!, "m02");
  assert.equal(await refusal(() => canonicalize(request(copy, workspace, { instrumentation: { async beforeProcess({ role }) {
    if (role === "source_video_digest") await unlink(copy.path); } } }))), "source_changed");
  await assertNothingPublished(workspace, "M02");
});

// ================================================================ authorization, consent and cache security
test("B1B-M03 only a consenting 1.1.0 root of exactly these bytes is canonicalized", async t => {
  const workspace = await scratch(t, "m03");
  assert.equal(await refusal(() => canonicalize(request(F.video!, workspace, { rootAuthorization: v1(F.video!) }))), "canonicalization_consent_required");
  assert.equal(await entries(join(workspace, ".local-media")), null, "nothing is created without consent");
  assert.equal(await refusal(() => canonicalize(request(F.video!, workspace, { rootAuthorization: root(F.video!, { contentHash: F.other!.contentHash }) }))), "source_mismatch");
  assert.equal(await refusal(() => canonicalize(request(F.video!, workspace, { rootAuthorization: root(F.video!, { sizeBytes: F.video!.sizeBytes + 1 }) }))), "source_mismatch");
  const { derivation, authorization } = (await canonicalOnce("video")).result;
  assert.ok(derivation !== undefined && authorization !== undefined);
  for (const value of [authorization, { ...root(F.video!), sourceType: "synthetic", authorizationBasis: "synthetic_generated" }, { manifestType: "AuthorizedFootage" }, null, "root"]) {
    assert.equal(await refusal(() => canonicalize(request(F.video!, workspace, { rootAuthorization: value }))), "authorization_invalid", JSON.stringify(value).slice(0, 60));
  }
  assert.equal(await refusal(() => canonicalize(request(F.video!, workspace, { allowedPurposes: ["local_reference_analysis"] }))), "request_invalid");
  assert.equal(await refusal(() => canonicalize(request(F.video!, workspace, { clock: { now: () => "2026-09-01T00:00:00.000Z" } }))), "request_invalid",
    "a derived record is never dated before its root");
  assert.equal(await entries(join(workspace, ".local-media", "canonical-v0", "objects")), null);
});

test("B1B-M04 cache identity is never authorization identity: each root gets its own derivation, and no consent means nothing", async t => {
  const workspace = await scratch(t, "m04"), x = await canonicalize(request(F.pcm!, workspace));
  const objects = await entries(store(workspace, "objects")), recordBytes = await readFile(recordPath(workspace, x.computationId!), "utf8");
  const y = await canonicalize(request(F.pcm!, workspace, { rootAuthorization: root(F.pcm!, OTHER) }));
  assert.deepEqual([y.cache, y.computationId], ["hit", x.computationId], "the same byte-producing work");
  assert.deepEqual((y.derivation as { scope: Json }).scope, OTHER);
  assert.notEqual((y.derivation as Json).derivationId, (x.derivation as Json).derivationId);
  assert.deepEqual([(y.authorization as Json).creatorId, (y.authorization as Json).projectId], [OTHER.creatorId, OTHER.projectId]);
  assert.deepEqual(((y.authorization as { derivedFrom: Json }).derivedFrom.rootAuthorization as Json).creatorId, OTHER.creatorId);
  assert.equal(await refusal(() => canonicalize(request(F.pcm!, workspace, { rootAuthorization: v1(F.pcm!, OTHER) }))), "canonicalization_consent_required");
  assert.deepEqual(await entries(store(workspace, "objects")), objects);
  assert.equal(await readFile(recordPath(workspace, x.computationId!), "utf8"), recordBytes, "the record names no scope and never changes");
  assert.doesNotMatch(recordBytes, /creator_b1b|project_b1b|canonicalizationConsent|derivationId|rootAuthorization/);
});

// ================================================================ locations
test("B1B-M05 source, tool and store locations are explicit, local and link-free; the store is never the source's directory", async t => {
  const workspace = await scratch(t, "m05");
  for (const sourcePath of ["relative/source.mp4", "https://example.com/source.mp4", "file:///C:/source.mp4", "\\\\server\\share\\source.mp4", `${fixtures}\\..\\fixtures\\n1-video.mp4`,
    fixtures, join(fixtures, "absent.mp4"), `${F.video!.path}\0`]) {
    assert.equal(await refusal(() => canonicalize(request(F.video!, workspace, { sourcePath }))), "source_location_invalid", sourcePath);
  }
  assert.equal(await refusal(() => canonicalize(request(F.video!, workspace, { toolRoot: workspace }))), "runtime_config_invalid");
  for (const workspaceRoot of ["relative/ws", "https://example.com/ws", "\\\\server\\share", join(workspace, "absent"), `${workspace}\\..\\x`]) {
    assert.equal(await refusal(() => canonicalize(request(F.video!, workspace, { workspaceRoot }))), "store_location_invalid", workspaceRoot);
  }
  // The store may never live in the directory that holds the source, nor may a source be read from inside the store.
  const copy = await copyOf(t, F.video!, "m05-same");
  assert.equal(await refusal(() => canonicalize(request(copy, join(copy.path, "..")))), "store_location_invalid");
  const holder = await scratch(t, "m05-inside"), inside = { ...F.video!, path: store(holder, "source.mp4") };
  await mkdir(store(holder), { recursive: true }); await copyFile(F.video!.path, inside.path);
  assert.equal(await refusal(() => canonicalize(request(inside, holder))), "store_location_invalid");
  // A link anywhere in the workspace or store path refuses (directory junctions need no privilege on this platform).
  const linked = await scratch(t, "m05-link"), target = await scratch(t, "m05-target");
  await symlink(target, join(linked, "ws"), "junction");
  assert.equal(await refusal(() => canonicalize(request(F.video!, join(linked, "ws")))), "store_location_invalid");
  const occupied = await scratch(t, "m05-file");
  await writeFile(join(occupied, ".local-media"), "not a directory");
  assert.equal(await refusal(() => canonicalize(request(F.video!, occupied))), "store_location_invalid");
  const junctioned = await scratch(t, "m05-store-link"), elsewhere = await scratch(t, "m05-store-target");
  await mkdir(join(junctioned, ".local-media")); await symlink(elsewhere, join(junctioned, ".local-media", "canonical-v0"), "junction");
  assert.equal(await refusal(() => canonicalize(request(F.video!, junctioned))), "store_location_invalid");
  assert.deepEqual(await entries(elsewhere), [], "nothing is written through a link");
});

// ================================================================ the verification methods
test("B1B-M06 the v0 verification methods bind exact timing as well as payloads, and exclude only the decoded SAR line", async () => {
  const digest = A["canonicalListingDigest"] as (text: string, kind: "video" | "audio") => string;
  const audio = await independentListing(F.aac!.path, "audio"), video = await independentListing(F.video!.path, "video");
  const base = { audio: digest(audio, "audio"), video: digest(video, "video") };
  assert.match(base.audio, /^[a-f0-9]{64}$/);
  const lines = (text: string) => text.split("\n");
  const edit = (text: string, at: (line: string) => boolean, change: (line: string) => string) => { let done = false;
    return lines(text).map(line => { if (!done && at(line)) { done = true; return change(line); } return line; }).join("\n"); };
  const row = (line: string) => /^0,/.test(line);
  const field = (line: string, index: number, value: string) => line.split(",").map((f, i) => i === index ? ` ${value}` : f).join(",");
  assert.notEqual(digest(edit(audio, row, l => field(l, 2, "-1023")), "audio"), base.audio, "one packet's pts moved by one tick");
  assert.notEqual(digest(edit(audio, row, l => field(l, 1, "-1023")), "audio"), base.audio, "one packet's dts");
  assert.notEqual(digest(edit(audio, row, l => field(l, 3, "1023")), "audio"), base.audio, "one packet's duration");
  assert.notEqual(digest(edit(audio, row, l => field(l, 5, "0".repeat(32))), "audio"), base.audio, "one packet's payload");
  assert.notEqual(digest(edit(audio, l => l.startsWith("#sample_rate"), () => "#sample_rate 0: 44100"), "audio"), base.audio);
  assert.notEqual(digest(edit(audio, l => l.startsWith("#tb"), () => "#tb 0: 1/96000"), "audio"), base.audio, "the time base gives the timestamps their meaning");
  assert.equal(digest(edit(video, l => l.startsWith("#sar"), () => "#sar 0: 1/1"), "video"), base.video, "the SAR line alone is excluded");
  assert.notEqual(digest(edit(video, row, l => field(l, 2, "1")), "video"), base.video, "one frame's pts");
  assert.notEqual(digest(edit(video, row, l => field(l, 5, "f".repeat(32))), "video"), base.video, "one frame's pixels");
  assert.notEqual(digest(edit(video, l => l.startsWith("#tb"), () => "#tb 0: 1/30"), "video"), base.video);
  for (const [text, kind] of [[`${audio}#extra: 1\n`, "audio"], [audio.replace("#hash: MD5", "#hash: CRC32"), "audio"], [video.replace("#media_type 0: video", "#media_type 0: audio"), "video"],
    [`${video}0, 1, 1, 512, 21600, nothex\n`, "video"], [video.replace(/\n/g, "\r\n"), "video"], ["", "video"]] as const) {
    assert.equal(await refusal(async () => digest(text, kind)), "digest_invalid");
  }
  // The method definitions are fixed: any change to them is a new method version, never a silent reinterpretation.
  const queries = A["CANONICAL_INGEST_QUERIES"] as Json;
  assert.deepEqual(Object.keys(queries).sort(), ["audioPackets", "decodedVideo", "probe"]);
  assert.match(JSON.stringify(queries.audioPackets), /"-c","copy","-f","framemd5"/);
  assert.match(JSON.stringify(queries.decodedVideo), /"-fps_mode","passthrough","-enc_time_base:v","demux","-f","framemd5"/);
});

// ================================================================ end to end with the owner-media registry (no permit: see the lifecycle and permit suites)
test("B1B-E01 a real canonical output registers beside its root and never outlives it", async t => {
  const { workspace, result } = await canonicalOnce("pcm");
  const output = result.output as { contentHash: string; sizeBytes: number };
  const registration = { artifactType: "OwnerMediaRegistration", artifactVersion: "0.2.0", stability: "internal_pre_stable",
    footage: { manifestType: "AuthorizedFootageSet", schemaVersion: "1.0.0", ...SCOPE, assets: [{ entryId: "clip_pcm", path: SPECS.pcm!.name, authorization: root(F.pcm!) }] },
    canonicalDerivatives: [{ entryId: "clip_pcm_canonical", rootEntryId: "clip_pcm", authorization: result.authorization, derivation: result.derivation }],
    renderAuthorization: { statement: ownerMedia.OWNER_CANONICAL_RENDER_AUTHORIZATION_STATEMENT, owner: { kind: "owner", actorId: "owner_b1b_media" }, renderIntents: ["final"],
      authorizedAt: "2026-10-01T00:00:00.000Z", expiresAt: null } };
  const create = authority.createOwnerMediaLifecycleAuthority as unknown as (input: Json) => Promise<authority.OwnerMediaLifecycleAuthority>;
  const registry = await create({ registration, baseDirectory: fixtures, clock: CLOCK, canonicalWorkspace: workspace });
  const rootId = `asset_${F.pcm!.contentHash}`, derivedId = `asset_${output.contentHash}`;
  assert.deepEqual(registry.declared.map(d => d.assetId).sort(), [rootId, derivedId].sort());
  assert.deepEqual((await registry.verify(derivedId)).contentHash, output.contentHash);
  registry.assertCurrent(derivedId, CLOCK.now());
  registry.requestDeletion(rootId);
  assert.throws(() => registry.assertCurrent(derivedId, CLOCK.now()), (e: unknown) => (e as { code?: string }).code === "lifecycle_deleted");
  void t;
});
