// A2-R02/R03: measured before A2 routing changed, using these exact generated bytes on the pinned toolchain. No owner footage.
import assert from "node:assert/strict";
import { test } from "node:test";
import { mkdir, mkdtemp, realpath } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { canonicalizeLocalMedia } from "../scripts/media-ingest-local.js";
import { N1_ARGV_TEMPLATE } from "../packages/media-ingest/index.js";
import { generatePlanFixture, sha256File } from "./support/canonical-media-fixtures.js";
import { observeMediaSpawns, PINNED_TOOL_ROOT } from "./support/edit-render-media.js";

const GOLDEN = [
  { audio: "none", source: "4dea66f4af25b485d35f0a7bfe5af716782c328d54d2f29e2caab919b8dffcd3", output: "8883e8862b0d3d5c1326d96bb71b50605494cedb4b146cc4e0b1ee307ad48c8d",
    computation: "canonical_media_computation_v0_4b7b18855a8f3dc81c510def9508df73e55e881e2d281e880102e77a6a760858",
    derivation: "canonical_media_derivation_v0_f9fd4dcd159febbc42ee7c1ed45d837142d579af3fd31b8236a7ec8b5c51796a" },
  { audio: "aac", source: "6c260ee15b4452426d61d6b263d324231462d087d122468557d69c33869aef40", output: "63d3c0965de04c1be88486fbf41c93457b6f82d5a9c3218c15f1208807795803",
    computation: "canonical_media_computation_v0_7e3d25050cb934dc38e84920631c2035e1c552b7849f87ddbfc5e880c1599e10",
    derivation: "canonical_media_derivation_v0_7faf8ec372d6e1f5522b832ce9f91325f1d78f788b630bcd89775c4a1aab4e36" },
] as const;
for (const golden of GOLDEN) test(`A2-R02/R03 frozen N1 ${golden.audio} keeps exact argv, bytes, identities and cache`, async () => {
  const base = await realpath(await mkdtemp(join(tmpdir(), "a2-n1-"))), generated = join(base, "generated"), workspaceRoot = join(base, "workspace");
  await mkdir(generated); await mkdir(workspaceRoot);
  const sourcePath = await generatePlanFixture(generated, "source.mp4", { sar: "unspecified", audio: golden.audio }), source = await sha256File(sourcePath);
  assert.equal(source.contentHash, golden.source);
  const request = { sourcePath, workspaceRoot, toolRoot: PINNED_TOOL_ROOT, clock: { now: () => "2026-10-07T00:00:00.000Z" },
    rootAuthorization: { manifestType: "AuthorizedFootage", schemaVersion: "1.1.0", ...source, sourceType: "owner_supplied", authorizationBasis: "owner_created",
      allowedPurposes: ["local_footage_analysis"], dateAdded: "2026-10-01T00:00:00.000Z", creatorId: "creator_n1_golden", projectId: "project_n1_golden",
      canonicalizationConsent: "local_media_canonicalization" } };
  const spawns = observeMediaSpawns(); let first;
  try { first = await canonicalizeLocalMedia(request); } finally { spawns.restore(); }
  assert.equal(first.outcome, "NORMALIZE_N1"); if (first.outcome !== "NORMALIZE_N1") assert.fail("legacy route required");
  assert.equal(first.output.contentHash, golden.output); assert.equal(first.computationId, golden.computation); assert.equal(first.derivation.derivationId, golden.derivation);
  const argv = spawns.calls.filter(c => c.arguments.includes("-fs")); assert.equal(argv.length, 1);
  assert.deepEqual(argv[0]!.arguments, N1_ARGV_TEMPLATE.map(t => t === "{input_fd}" ? "3" : t === "{output_fd}" ? "4" : t === "{max_output_bytes}" ? String(2 * source.sizeBytes + 1_048_576) : t));
  const second = await canonicalizeLocalMedia(request); assert.equal(second.outcome, "NORMALIZE_N1"); if (second.outcome !== "NORMALIZE_N1") assert.fail("legacy cache required");
  assert.equal(second.cache, "hit"); assert.deepEqual(second.derivation, first.derivation); assert.deepEqual(second.authorization, first.authorization);
});
