// E1 RED first. Generated bytes only; the ordinary ingest API must measure and publish without issuing authority.
import assert from "node:assert/strict";
import { before, after, test } from "node:test";
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import * as local from "../scripts/media-ingest-local.js";
import { cdBase, cdSeed, cdTransform, cdRequest } from "./support/canonical-lossless-cd.js";
import { D4_ELEMENTS } from "./support/canonical-pixel-reference.js";
import { registerGenerated, verifyGenerated, declareGeneratedChroma, declareGeneratedAvCenter } from "./support/canonical-reencode-media.js";
import { generatePlanFixture, generatePlanVariant, sha256File } from "./support/canonical-media-fixtures.js";
import { appendChromaFixtureBox, patchPlanFixture } from "./support/canonical-plan-media.js";
import { MATRIX_FOR_D4 } from "./support/canonical-reencode-media.js";
import { derivedRecord } from "./support/canonical-media.js";
import { FootageAuthorizationSchema } from "../packages/footage-analyzer/protocol.js";
import { type ChromaSafeDerivation } from "../packages/media-ingest/chroma.js";
import { canonicalObjectName } from "../packages/edit-render/owner-media.js";
type Published = { outcome: "PUBLISHED_VERIFIED_NOT_AUTHORIZED"; derivation: ChromaSafeDerivation; computationId: string;
  output: local.SourceIdentity; cache: "miss" | "hit"; renderAuthority: "not_registered"; record: { output: { format: { format: string; majorBrand: string } } } };
let sources = "", stores = ""; const seeds: Record<string, string> = {}, receipt: unknown[] = [];
before(async () => { sources = await cdBase("ef-src-"); stores = await cdBase("ef-w-");
  for (const codec of ["h264", "hevc"] as const) seeds[codec] = await cdSeed(sources, codec); });
after(async () => { await writeFile(join(stores, "routing-receipt.json"), JSON.stringify(receipt, null, 2), { flag: "wx" }); });
async function request(source: string, name: string) { const workspace = join(stores, name); await mkdir(workspace);
  return cdRequest(source, workspace); }
async function prove(req: local.CanonicalIngestRequest) {
  const before = await sha256File(req.sourcePath), result = await local.canonicalizeLocalMedia(req);
  assert.equal(result.outcome, "PUBLISHED_VERIFIED_NOT_AUTHORIZED"); const p = result as unknown as Published;
  assert.equal(p.renderAuthority, "not_registered"); assert.equal("authorization" in result, false); assert.equal("outputPath" in result, false);
  const output = join(req.workspaceRoot, ".local-media", "canonical-v0", "objects", canonicalObjectName(p.output.contentHash));
  assert.deepEqual(await sha256File(output), { contentHash: p.output.contentHash, sizeBytes: p.output.sizeBytes });
  const independent = await verifyGenerated(req.sourcePath, registerGenerated(output), p.derivation.plan.samplePlan.transform,
    p.derivation.sampleDerivation.source.facts, sources);
  assert.deepEqual(p.derivation.sampleDerivation.verification.pixels, independent.pixels);
  assert.equal(p.derivation.outputChroma.streamReported, "center"); assert.equal(p.derivation.plan.planVersion, "1.1.0");
  assert.deepEqual(await sha256File(req.sourcePath), before);
  assert.equal((await readdir(join(req.workspaceRoot, ".local-media", "canonical-v0", "objects"))).length, 1);
  assert.equal((await readdir(join(req.workspaceRoot, ".local-media", "canonical-v0", "computations"))).length, 1);
  assert.deepEqual(await readdir(join(req.workspaceRoot, ".local-media", "canonical-v0", "pending")), []);
  receipt.push({ source: before, output: p.output, computationId: p.computationId, cache: p.cache, transform: p.derivation.plan.samplePlan.transform });
  return p;
}
test("EF-ROUTE-DIRECT: conforming H.264 stays DIRECT without chroma children or a store", async () => {
  const req = await request(seeds.h264!, "direct"), roles: string[] = [];
  const r = await local.canonicalizeLocalMedia({ ...req, instrumentation: { beforeProcess: async e => { roles.push(e.role); } } });
  assert.equal(r.outcome, "DIRECT"); assert.equal(roles.includes("canonicalize"), false);
  await assert.rejects(() => readdir(join(req.workspaceRoot, ".local-media")), { code: "ENOENT" });
});
test("EF-ROUTE-HEVC-identity: complete lossless publication through ordinary ingest", async () => { await prove(await request(seeds.hevc!, "identity")); });
for (const codec of ["h264", "hevc"] as const) for (const transform of D4_ELEMENTS)
test("EF-ROUTE-" + codec + "-" + transform + ": every eligible D4 preserves all output samples", async () => {
  const source = await cdTransform(sources, seeds[codec]!, "route-" + codec + transform, transform);
  await prove(await request(source, codec + transform));
});
test("EF-ROUTE-exact-remux-precedence: timeline rebase uses the accepted PLAN path", async () => {
  const source = await generatePlanVariant(seeds.h264!, join(sources, "remux.mp4"), { rebase: true });
  const req = await request(source, "remux"), r = await local.canonicalizeLocalMedia(req);
  assert.equal(r.outcome, "PLAN"); if (r.outcome !== "PLAN") assert.fail();
  assert.equal(r.derivation.artifactVersion, "0.2.0"); assert.equal(r.authorization.sourceType, "system_canonicalized");
});
for (const siting of [0, 2, 3, 4, 5] as const) test("EF-ROUTE-conservative-siting-" + siting + ": retains DEFER and never encodes", async () => {
  const source = await declareGeneratedChroma(seeds.hevc!, join(sources, "siting-" + siting + ".mp4"), "hevc", siting);
  const req = await request(source, "siting-" + siting); let encodes = 0;
  const r = await local.canonicalizeLocalMedia({ ...req, instrumentation: { beforeProcess: async e => { if (e.role === "canonicalize") encodes++; } } });
  assert.equal(r.outcome, "DEFER"); assert.equal(encodes, 0); assert.ok(r.planning?.evaluation.findings.length);
});
test("EF-ROUTE-default: missing explicit declaration stays DEFER", async () => {
  const source = await generatePlanFixture(sources, "default.mp4", { hevc: true });
  assert.equal((await local.canonicalizeLocalMedia(await request(source, "default"))).outcome, "DEFER");
});
for (const color of ["bt601", "hdr"] as const) test("EF-ROUTE-frozen-refusal-" + color, async () => {
  const source = await generatePlanFixture(sources, color + ".mp4", { hevc: true, color });
  assert.equal((await local.canonicalizeLocalMedia(await request(source, color))).outcome, "REFUSE");
});
test("EF-ROUTE-conflicting-container: unknown interpretation carrier remains REFUSE", async () => {
  const source = registerGenerated(await appendChromaFixtureBox(seeds.hevc!, join(sources, "conflict.mp4"), "cloc"));
  const r = await local.canonicalizeLocalMedia(await request(source, "conflict")); assert.equal(r.outcome, "REFUSE");
});
for (const key of ["plan", "argv", "admission", "facts", "handle", "outputPath"]) test("EF-ROUTE-caller-proof-refused-" + key, async () => {
  const req = await cdRequest(seeds.hevc!, stores);
  await assert.rejects(() => local.canonicalizeLocalMedia({ ...req, [key]: {} } as local.CanonicalIngestRequest),
    (e: unknown) => e instanceof local.CanonicalIngestError && e.code === "request_invalid");
});
test("EF-ROUTE-root-boundaries: invalid, nonconsenting and derived roots refuse", async () => {
  const req = await cdRequest(seeds.hevc!, stores), root = req.rootAuthorization as Record<string, unknown>;
  await assert.rejects(() => local.canonicalizeLocalMedia({ ...req, rootAuthorization: {} }), /valid AuthorizedFootage/);
  const old: Record<string, unknown> = { ...root, schemaVersion: "1.0.0" }; delete old.canonicalizationConsent;
  await assert.rejects(() => local.canonicalizeLocalMedia({ ...req, rootAuthorization: old }), /consent|consenting/);
  await assert.rejects(() => local.canonicalizeLocalMedia({ ...req, rootAuthorization: { ...root, sourceType: "system_canonicalized" } }),
    (e: unknown) => e instanceof local.CanonicalIngestError && e.code === "authorization_invalid");
  const validDerived = derivedRecord(await sha256File(seeds.hevc!)); assert.equal(FootageAuthorizationSchema.safeParse(validDerived).success, true);
  await assert.rejects(() => local.canonicalizeLocalMedia({ ...req, rootAuthorization: validDerived }), /derivation depth is exactly one/);
});
test("EF-ROUTE-request-snapshot: getters, clock, authorization and hooks cannot redirect after an await", async () => {
  const req = await request(seeds.hevc!, "snapshot"), root = req.rootAuthorization as Record<string, unknown>, reads: Record<string, number> = {};
  let clockCalls = 0, redirected = false; const clock = { now: () => { clockCalls++; return clockCalls === 1 ? "2026-10-08T00:00:00.000Z" : "1900-01-01T00:00:00.000Z"; } };
  const hooks = { beforeProcess: async () => { root.contentHash = "f".repeat(64); root.creatorId = "creator_attacker";
    hooks.beforeProcess = async () => { redirected = true; }; } };
  const fields = { ...req, clock, instrumentation: hooks }, malicious = {} as local.CanonicalIngestRequest;
  for (const [name, value] of Object.entries(fields)) Object.defineProperty(malicious, name, { enumerable: true, get: () => {
    reads[name] = (reads[name] ?? 0) + 1; if (reads[name]! > 1) throw new Error("caller field reread: " + name); return value;
  } });
  const p = await local.canonicalizeLocalMedia(malicious); assert.equal(p.outcome, "PUBLISHED_VERIFIED_NOT_AUTHORIZED");
  assert.equal(clockCalls, 1); assert.equal(redirected, false); assert.ok(Object.values(reads).every(n => n === 1));
  const d = (p as unknown as Published).derivation; assert.equal(d.sampleDerivation.scope.creatorId, "creator_cd_generated");
  assert.equal(d.sampleDerivation.source.contentHash, (await sha256File(req.sourcePath)).contentHash);
  assert.equal((await readFile(req.sourcePath)).length, d.sampleDerivation.source.sizeBytes);
});
test("EF-ROUTE-PCM-MOV: actual MOV payload under the frozen .mp4 namespace is truthfully identified and reverified", async () => {
  const seed = registerGenerated(await generatePlanFixture(sources, "pcm.mov", { hevc: true, audio: "pcm", sei: "encoder" }));
  const source = await declareGeneratedAvCenter(seed, join(sources, "pcm-center.mov"), "hevc", 90000, "mov");
  const req = await request(source, "pcm"), a = await prove(req), b = await local.canonicalizeLocalMedia(req) as unknown as Published;
  assert.equal(a.record.output.format.format, "mov"); assert.equal(a.record.output.format.majorBrand, "qt  "); assert.equal(b.cache, "hit");
  assert.equal(b.record.output.format.format, "mov"); assert.equal(a.derivation.sampleDerivation.verification.audioPackets?.sourceDigest,
    a.derivation.sampleDerivation.verification.audioPackets?.outputDigest);
});
test("EF-ROUTE-true-VFR: unsupported findings remain deferred without an encoder", async () => {
  const { generateFixture } = await import("./support/canonical-media-fixtures.js");
  const source = await generateFixture(sources, "vfr.mp4", { audio: "none", sar: "square", timing: "vfr", profileColor: true });
  const req = await request(source, "vfr"); let encodes = 0;
  const r = await local.canonicalizeLocalMedia({ ...req, instrumentation: { beforeProcess: async e => { if (e.role === "canonicalize") encodes++; } } });
  assert.equal(r.outcome, "DEFER"); assert.equal(encodes, 0);
});
test("EF-ROUTE-all-five: full original repair composition survives publication and a freshly reconstructed cache hit", async () => {
  const seed = registerGenerated(await generatePlanFixture(sources, "all-five-seed.mp4", { hevc: true, audio: "aac", sar: "unspecified", sei: "encoder" }));
  const variant = registerGenerated(await generatePlanVariant(seed, join(sources, "all-five-timing.mp4"), { select: true, rebase: true, snap: true, retime: true, audio: true }));
  const center = await declareGeneratedAvCenter(variant, join(sources, "all-five-center.mp4"), "hevc", 90000, "mp4", true);
  const source = registerGenerated(await patchPlanFixture(center, join(sources, "all-five-input.mp4"), { matrix: MATRIX_FOR_D4.rotate_90_cw }));
  const req = await request(source, "all-five"), a = await prove(req); let encodes = 0;
  const b = await local.canonicalizeLocalMedia({ ...req, instrumentation: { beforeProcess: async e => { if (e.role === "canonicalize") encodes++; } } }) as unknown as Published;
  assert.deepEqual(a.derivation.plan.samplePlan.operations.map(o => o.op), ["SELECT_AV_STREAMS", "REBASE_TIMELINE_ZERO", "DECLARE_SQUARE_SAMPLE_ASPECT", "SNAP_VIDEO_TIMESTAMPS", "RETIME_AUDIO_CONTIGUOUS"]);
  assert.equal(b.cache, "hit"); assert.equal(encodes, 0); assert.deepEqual(a.record, b.record);
  assert.deepEqual(a.derivation.sampleDerivation.verification, b.derivation.sampleDerivation.verification);
});
