// A2-O structural registration tests: opaque generated bytes and synthetic A1 derivations, not media proof or owner footage.
import assert from "node:assert/strict";
import { test } from "node:test";
import { mkdir, mkdtemp, readFile, realpath, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { buildCanonicalPlanDerivedAuthorization } from "../packages/media-ingest/index.js";
import { OwnerMediaCanonicalRegistrationSchema, ownerMediaCanonicalDeclarations } from "../packages/edit-render/owner-media.js";
import { createOwnerMediaLifecycleAuthority } from "../scripts/edit-render-owner-media-authority-local.js";
import { composedSource, planChain } from "./support/canonical-facts.js";
import { deterministicBytes, sha256Hex } from "./support/edit-runtime.js";
import { plantCanonical, registration02, rootOf, type Json } from "./support/owner-media-canonical.js";

const clock = { now: () => "2026-10-07T00:00:00.000Z" };
async function setup() {
  const base = await realpath(await mkdtemp(join(tmpdir(), "a2-owner-"))), workspace = join(base, "workspace"), originals = join(base, "originals");
  await mkdir(workspace); await mkdir(originals);
  const source = deterministicBytes("a2-root", 4021), output = deterministicBytes("a2-derived", 4031), root = rootOf(source);
  await writeFile(join(originals, "source.mp4"), source);
  const { derivation } = planChain(composedSource(), { rootAuthorization: root, outputHash: sha256Hex(output), outputSize: output.length });
  const authorization = buildCanonicalPlanDerivedAuthorization({ derivation, dateAdded: "2026-10-01T00:00:00.000Z" }) as unknown as Json;
  const registration = registration02({ originals: [{ entryId: "clip_root", path: "source.mp4", authorization: root }],
    derivatives: [{ entryId: "clip_derived", rootEntryId: "clip_root", derivation, authorization }] });
  const planted = await plantCanonical(workspace, derivation, output);
  return { registration, workspace, originals, derivation, authorization, planted, source, output,
    rootId: `asset_${sha256Hex(source)}`, derivedId: `asset_${sha256Hex(output)}` };
}
const make = (s: Awaited<ReturnType<typeof setup>>) => createOwnerMediaLifecycleAuthority({ registration: s.registration, baseDirectory: s.originals, canonicalWorkspace: s.workspace, clock });
test("A2-O02/O04/O05 a v0.2 derivative registers with its root, exact plan and computation record", async () => {
  const s = await setup(); assert.ok(OwnerMediaCanonicalRegistrationSchema.safeParse(s.registration).success);
  const d = ownerMediaCanonicalDeclarations(s.registration).derivatives[0]!;
  assert.equal(d.recipeId, (s.derivation.plan as Json).planId); assert.equal(d.computationId, s.derivation.computationId);
  const authority = await make(s); assert.equal((await authority.verify(s.derivedId)).contentHash, sha256Hex(s.output));
  assert.equal((await authority.verify(s.rootId)).contentHash, sha256Hex(s.source)); authority.assertCurrent(s.derivedId, clock.now());
});
test("A2-O03/O04 root absence or recipe/plan mismatch refuses", async () => {
  const s = await setup(), missing = structuredClone(s.registration); (missing.footage as Json).assets = [];
  assert.equal(OwnerMediaCanonicalRegistrationSchema.safeParse(missing).success, false);
  await assert.rejects(make({ ...s, registration: missing }));
  const absentReference = structuredClone(s.registration);
  (absentReference.canonicalDerivatives as Json[])[0]!.rootEntryId = "root_not_declared";
  assert.equal(OwnerMediaCanonicalRegistrationSchema.safeParse(absentReference).success, false);
  await assert.rejects(make({ ...s, registration: absentReference }));
  const wrong = structuredClone(s.registration), derivative = (wrong.canonicalDerivatives as Json[])[0]!;
  ((derivative.authorization as Json).derivedFrom as Json).recipeId = "plan_other";
  assert.equal(OwnerMediaCanonicalRegistrationSchema.safeParse(wrong).success, false);
  await assert.rejects(make({ ...s, registration: wrong }));
});
test("A2-O05/O06 exact record and output rehash are mandatory", async () => {
  const s = await setup(); await make(s);
  const record = await readFile(s.planted.recordPath); await writeFile(s.planted.recordPath, "{}"); await assert.rejects(make(s));
  await writeFile(s.planted.recordPath, record);
  const bytes = Buffer.from(s.output); bytes[20] = bytes[20]! ^ 1; await writeFile(s.planted.objectPath, bytes); await assert.rejects(make(s));
});
test("A2-O08/O09/O10 the existing one-root lifecycle governs v0.2", async () => {
  const s = await setup(), rootDeleted = await make(s); rootDeleted.requestDeletion(s.rootId);
  assert.throws(() => rootDeleted.assertCurrent(s.derivedId, clock.now()));
  const derivedDeleted = await make(s); derivedDeleted.requestDeletion(s.derivedId);
  assert.throws(() => derivedDeleted.assertCurrent(s.derivedId, clock.now())); derivedDeleted.assertCurrent(s.rootId, clock.now());
  for (const [id, other] of [[s.rootId, s.derivedId], [s.derivedId, s.rootId]]) {
    const a = await make(s); a.setExpiry(id!, "2026-10-06T00:00:00.000Z"); a.setExpiry(other!, "2026-10-08T00:00:00.000Z");
    assert.throws(() => a.assertCurrent(s.derivedId, clock.now()));
  }
});
